### ISSUE TITLE
Subclim commands not working

### ISSUE THREAD

**Issue by aparra** [JulianEberius/Subclim#20]
Subclim commands not working for me. When I hit ctr+alt+i or ctr+alt+space an error is printed in console. I'm using ST3 and dclim 2.3.2

Writing file /Users/anderson/Desktop/Hello.java with encoding UTF-8 (atomic)
Traceback (most recent call last):
  File "subclim_plugin in /Users/anderson/Library/Application Support/Sublime Text 3/Installed Packages/Subclim.sublime-package", line 46, in worker
  File "subclim_plugin in /Users/anderson/Library/Application Support/Sublime Text 3/Installed Packages/Subclim.sublime-package", line 653, in async_validate_task
  File "eclim in /Users/anderson/Library/Application Support/Sublime Text 3/Installed Packages/Subclim.sublime-package", line 137, in update_java_src
  File "eclim in /Users/anderson/Library/Application Support/Sublime Text 3/Installed Packages/Subclim.sublime-package", line 70, in call_eclim
  File "X/subprocess.py", line 818, in **init**
  File "X/subprocess.py", line 1363, in _execute_child
TypeError: Can't convert 'NoneType' object to str implicitly
Traceback (most recent call last):
  File "subclim_plugin in /Users/anderson/Library/Application Support/Sublime Text 3/Installed Packages/Subclim.sublime-package", line 46, in worker
  File "subclim_plugin in /Users/anderson/Library/Application Support/Sublime Text 3/Installed Packages/Subclim.sublime-package", line 719, in async_find_imports_task
  File "subclim_plugin in /Users/anderson/Library/Application Support/Sublime Text 3/Installed Packages/Subclim.sublime-package", line 739, in call_eclim
  File "eclim in /Users/anderson/Library/Application Support/Sublime Text 3/Installed Packages/Subclim.sublime-package", line 137, in update_java_src
  File "eclim in /Users/anderson/Library/Application Support/Sublime Text 3/Installed Packages/Subclim.sublime-package", line 70, in call_eclim
  File "X/subprocess.py", line 818, in __init__
  File "X/subprocess.py", line 1363, in _execute_child
TypeError: Can't convert 'NoneType' object to str implicitly
Traceback (most recent call last):
  File "subclim_plugin in /Users/anderson/Library/Application Support/Sublime Text 3/Installed Packages/Subclim.sublime-package", line 46, in worker
  File "subclim_plugin in /Users/anderson/Library/Application Support/Sublime Text 3/Installed Packages/Subclim.sublime-package", line 653, in async_validate_task
  File "eclim in /Users/anderson/Library/Application Support/Sublime Text 3/Installed Packages/Subclim.sublime-package", line 137, in update_java_src
  File "eclim in /Users/anderson/Library/Application Support/Sublime Text 3/Installed Packages/Subclim.sublime-package", line 70, in call_eclim
  File "X/subprocess.py", line 818, in __init__
  File "X/subprocess.py", line 1363, in _execute_child

**Comment by toddwildey** [comment]
Also having this issue.  OS X 10.9.5, ST3.
